name: "Setup Clang & Dependencies"
description: "Installs dependencies and Clang for MTK kernel build"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev libncurses-dev libelf-dev wget git make python3

    - name: Download AOSP Clang
      shell: bash
      run: |
        if [ ! -d "clang" ]; then
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 \
            --depth=1 -b master clang-bin
          # Using r450784d as requested
          mv clang-bin/clang-r450784d clang
        fi

    - name: Set Environment
      shell: bash
      run: |
        # Add Clang bin to PATH so 'make' finds 'clang' and 'ld.lld' automatically
        echo "$(pwd)/clang/bin" >> $GITHUB_PATH
        
        # Set core variables
        echo "ARCH=arm64" >> $GITHUB_ENV
        echo "SUBARCH=arm64" >> $GITHUB_ENV
        echo "OS=linux" >> $GITHUB_ENV
